name: add-autoresponse
description: Add an automatic response to new issues or pull requests.
branding:
  icon: message-circle
  color: red

inputs:
  respondableId:
    description: The id of the issue or pull request
    required: true
  shouldClose:
    description: close the issue as well
    required: true
    default: false
  response:
    description: The response to be left on the issue or pull request
    required: true
  author:
    description: The username of the issue author
    required: true
  exemptedAuthors:
    description: Array of exempt usernames

runs:
  using: 'node12'
  main: 'index.js'
